import { Footer, Header } from "@/components";
import "../assets/globals.scss";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import cn from "classnames";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "flex flex-col min-h-screen")}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
